sudo: required
services: 
    - docker
    
before_install:
    - docker build -t kirito70/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kirito70/docker-react npm run test -- --coverage


deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "react-frontend"
    env: "ReactFrontend-env"
    bucket_name: "elasticbeanstalk-us-east-2-173878008449"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"