sudo: required
services: 
    - docker
    
before_install:
    - docker build -t kirito70/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kirito70/docker-react npm run test -- --coverage
